---
driver:
  name: docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  require_chef_for_busser: true

platforms:
  - name: centos-6.4

suites:
  - name: webserver
    provisioner:
      manifest: site.pp
